import Head from "next/head";

import { gql } from "@apollo/client";
import client from "../apollo-client";

import Categories from "../components/Categories";
import CategoriesNav from "../components/CategoriesNav";
import Favorites from "../components/Favorites";
import Search from "../components/Search";
import Header from "../components/Header";
import NotFound from "../components/NotFound";

export async function getStaticProps() {
  const { data } = await client.query({
    query: gql`
      query Categories {
        categories {
          id
          name
          image
          count
          slug
        }
      }
    `,
  });

  return {
    props: {
      categories: data.categories,
    },
  };
}

export default function Home({ categories }) {
  // FIXME: do this in graphql
  const checkCountProperty = categories.filter((e) => e.count);
  const sortByRecipeCount = checkCountProperty.sort(
    (a, b) => b.count - a.count
  );

  return (
    <div>
      <Head>
        <title>Pinoy Recipes</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />

      <main>
        <Search />
        <CategoriesNav
          categories={sortByRecipeCount
            .filter(
              (e) =>
                e.id != "24" &&
                e.id != "2" &&
                e.id != "11" &&
                e.id != "87" &&
                e.id != "88" &&
                e.id != "18"
            )
            .slice(0, 8)}
        />
        <NotFound />
      </main>
    </div>
  );
}
