import React from "react";
import { useRouter } from "next/router";
import Head from "next/head";

import Header from "../../../components/Header";
import CategoriesNav from "../../../components/CategoriesNav";
import Search from "../../../components/Search";
import Recipes from "../../../components/Recipes";

import { gql } from "@apollo/client";
import client from "../../../apollo-client";

export async function getServerSideProps() {
  const { data } = await client.query({
    query: gql`
      query Recipes {
        recipes {
          id
          title
          cook_time
          categories
          image
          slug
        }
      }
    `,
  });

  return {
    props: {
      recipes: data.recipes,
    },
  };
}

function Category({ recipes }) {
  // FIXME: do this in graphql
  const router = useRouter();
  const { category_id } = router.query;
  const withCookTimeFilter = recipes.filter((e) => e.cook_time);
  const filterByCategoryId = withCookTimeFilter.filter((recipe) =>
    recipe.categories.includes(Number(category_id))
  );
  console.log(filterByCategoryId);

  return (
    <>
      <Head>
        <title>Category</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />

      <main>
        <Search />
        <Recipes recipes={filterByCategoryId} />
      </main>
    </>
  );
}

export default Category;
