import React from "react";
import { useRouter } from "next/router";
import Head from "next/head";

import Header from "../../../components/Header";
import Search from "../../../components/Search";
import Recipe from "../../../components/Recipe";

import { gql } from "@apollo/client";
import client from "../../../apollo-client";

export async function getServerSideProps(context) {
  console.log(context);
  const { recipe_id } = context.query;
  const { data } = await client.query({
    query: gql`
      query Recipe {
        getRecipeById(recipeId: ${Number(recipe_id)}) {
          id
          title
          cook_time
          categories
          image
          slug
          prep_time
          ingredients
          nutritions
          description
          servings
          instructions
          related
        }
      }
    `,
  });

  return {
    props: {
      recipe: data.getRecipeById,
    },
  };
}

function RecipePage({ recipe }) {
  console.log(recipe);
  return (
    <>
      <Head>
        <title>{recipe.titl}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />

      <main>
        <Search />
        <Recipe recipe={recipe} />
      </main>
    </>
  );
}

export default RecipePage;
